// m-koa/m-book/src/views/MyBook.vue
<template>
  <div>
    <div v-for="(item, index) in myBook" :key="item.id">
      <input type="checkbox" :checked="item.checked" @change="handleChecked(index, $event)" :id="item.id">
      <label :for="item.id">{{item.title}}</label>
      ,￥{{item.price}} 
      <button @click="handleSub(index)">-</button> <span>{{item.count}}</span> <button @click="handleAdd(index)">+</button>
      <button @click="handleDelete(index)">删除</button>
    </div>
    <div>
      <input type="checkbox" :checked="total.selectAll" id="m-select-all" @change="handleSelectAll($event)">
      <label for="m-select-all">全选</label> <button @click="handleDeleteAll()">删除</button>
    </div>
    <div>
      总价：￥{{total.totalPrice}}，总数：{{total.totalCount}}
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    myBook() {
      return this.$store.state.myBook
    },
    total() {
      let myBook = this.$store.state.myBook
      let totalPrice = 0, totalCount = 0
      myBook.filter(item => item.checked).forEach(item => {
        totalCount += item.count
        totalPrice += item.count * item.price
      })
      return {
        totalPrice,
        totalCount,
        selectAll: myBook.filter(item => item.checked).length === myBook.length
      }
    }
  },
  methods: {
    handleDelete(index) {
      this.myBook.splice(index, 1)
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleDeleteAll() {
      let myBook = this.myBook.filter(item => !item.checked)
      this.$store.commit({ type: 'setState', key: 'myBook', value: myBook })
    },
    handleAdd(index) {
      this.myBook[index].count += 1
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleSub(index) {
      if (this.myBook[index].count > 1) {
        this.myBook[index].count -= 1
        this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
      }
    },
    handleChecked(index, e) {
      this.myBook[index].checked = e.target.checked
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleSelectAll(e) {
      this.myBook.forEach(item => {
        item.checked = e.target.checked 
      })
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    }
  },
  updated() {
    this.$store.dispatch({ type: 'updateMyBook', myBook: this.myBook })
  },
  mounted() {
    this.$store.dispatch({ type: 'getMyBook' })
  }
}
</script>

<style>

</style>

// m-react-app-test/src/views/MyBook.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import Api from '../api'

class MyBook extends Component {
  //选中某一本书，或者取消选中
  handleSelect(index, e) {
    let { bookList } = this.props
    bookList[index].checked = e.target.checked
    this.props.setState('bookList', bookList)
  }

  //全选，包括联动
  handleSelectAll(e) {
    let { bookList } = this.props

    bookList.forEach(item => {
      item.checked = e.target.checked
    })
    this.props.setState('bookList', bookList)
  }

  //删除多个
  handleDeleteSelected() {
    let { bookList } = this.props
    let ids = bookList.filter(item => item.checked).map(item => item.id)
    Api.bookDelete({ids}).then(res => {
      if (res.data.code === 200) {
        this.props.setState('bookList', res.data.data)
      }
    })
  }

  //删除单个
  handleDelete(ids) {
    Api.bookDelete({ids}).then(res => {
      if (res.data.code === 200) {
        this.props.setState('bookList', res.data.data)
      }
    })
  }

  //加
  handleAdd(index) {
    let { bookList } = this.props
    bookList[index].count += 1
    let bookListNew = JSON.parse(JSON.stringify(bookList))
    this.props.setState('bookList', bookListNew)
  }

  //减
  handleSub(index) {
    let { bookList } = this.props
    if (bookList[index].count > 1) {
      bookList[index].count -= 1
      let bookListNew = JSON.parse(JSON.stringify(bookList))
      this.props.setState('bookList', bookListNew)
    }
  }

  //存到后端
  handleUpdateBookList() {
    let { bookList } = this.props
    Api.bookUpdate({bookListNew:bookList}).then(res => {

    })
  }

  //更新完成
  componentDidUpdate() {
    this.handleUpdateBookList()
  }

  //挂载，从接口里获取书包的数据，然后放到redux里
  componentDidMount() {
    Api.getBookList().then(res => {
      if (res.data.code === 200) {
        this.props.setState('bookList', res.data.data)
      }
    })
  }
  
  render() {
    let { bookList } = this.props
    const bookListDom = bookList.map((item, index) => (
      <div key={item.id}>
        <input type="checkbox" checked={ item.checked }  onChange={this.handleSelect.bind(this, index)}></input>
        {item.title},价格：{item.price}元，<button onClick={this.handleSub.bind(this, index)}>-</button>{item.count}<button onClick={this.handleAdd.bind(this, index)}>+</button>
        <button onClick={this.handleDelete.bind(this, [item.id])}>删除</button></div>
    )) 

    let totalPrice = 0, totalCount = 0
    bookList.filter(item => item.checked).forEach(item => {
      totalCount += item.count
      totalPrice += item.count * item.price
    })
    let count = bookList.filter(item => item.checked).length
    return (
      <div>
        <input type="checkbox" checked={bookList.length === count} onChange={this.handleSelectAll.bind(this)} ></input> 全选
        <button onClick={this.handleDeleteSelected.bind(this)}>删除选中的</button>
        {bookListDom}
        <div>总价：{totalPrice}元，总数：{totalCount}</div>
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    bookList: state.bookList,
    a: []
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBook)
