// m-app-router-test/src/views/MyBook.vue
<template>
  <div>
    <div v-for="item in bookList" :key="item.id">
      {{item.title}}
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data() {
    return {
      bookList: []
    }
  },
  mounted() {
    axios({
      url: '/api/get_my_book'
    }).then(res => {
      if (res.data.code === 200) {
        this.bookList = res.data.data
      }
    })
  }
}
</script>

<style>

</style>

// m-react-app/src/views/MyBook.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import axios from 'axios'

class MyBook extends Component {

  componentDidMount() {
    axios({
      url: '/api/get_my_book'
    }).then(res => {
      if (res.data.code === 200) {
        this.props.onSetState('myBook', res.data.data)
      }
    })
  }

  render() {
    let { myBook } = this.props

    let myBookDom = myBook.map(item => (
      <div key={item.id}>{item.title}</div>
    ))

    return (
      <div>
        {myBookDom}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    myBook: state.myBook
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBook)
