// m-react-app-test/src/components/Nav.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import axios from 'axios'

class Nav extends Component {

  handleNav(index, id) {
    this.props.setState('currentIndex', index)
    this.props.setState('currentId', id)
  }

  componentDidMount() {
    axios({
      url: '/api/nav'
    }).then(res => {
      if (res.data.code === 200) {
        this.props.setState('navList', res.data.data)
      }
    })
  }
  render() {
    let { navList, currentIndex } = this.props

    let navListDom = navList.map((item, index) => (
      <span key={item.id} className={"m-nav-item " + (currentIndex === index ? 'active' : '')} 
        onClick={this.handleNav.bind(this, index, item.id)}>
        {item.title}
      </span>))

    return (
      <div>
        {navListDom}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    navList: state.navList,
    currentIndex: state.currentIndex
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Nav)

// m-koa/m-book/src/components/Nav.vue
<template>
  <div>
    <span
      v-for="item in navList"
      :key="item.id"
      class="m-nav-item"
      :class="{active: currentId === item.id}"
      @click="handleNav(item.id)"
    >{{item.title}}</span>
  </div>
</template>

<script>
export default {
  computed: {
    navList() {
      return this.$store.state.navList;
    },
    currentId() {
      return this.$store.state.currentId;
    }
  },
  methods: {
    handleNav(id) {
      this.$store.commit({ type: 'setState', key: 'currentId', value: id })
      this.$store.dispatch({ type: 'getList', id })
    }
  }
};
</script>

<style>
</style>
