// m-react-app/src/views/Detail.js
import React, { Component } from 'react'
import axios from 'axios'

export default class Detail extends Component {
  constructor(props) {
    super(props)
    this.state = {
      detail: {}
    }
  }

  handleAdd() {
    let { detail } = this.state
    axios({
      url: '/api/add_book',
      data: {
        item: detail
      },
      method: 'post'
    }).then(res => {
      if (res.data.code === 200) {
        let { id } = this.props.match.params
        axios({
          url: `/api/detail?id=${id}`
        }).then(res => {
          if (res.data.code === 200) {
            this.setState({
              detail: res.data.data
            })
          }
        })
      }
    })
  }

  componentDidMount() {
    let { id } = this.props.match.params
    axios({
      url: `/api/detail?id=${id}`
    }).then(res => {
      if (res.data.code === 200) {
        this.setState({
          detail: res.data.data
        })
      }
    })
  }

  render() {
    let { detail } = this.state
    return (
      <div>
        <img src={detail.avatar}></img><button className={'m-add-btn ' + (detail.is_in_my_book ? "": 'active')} onClick={this.handleAdd.bind(this)}>收藏</button>
      </div>
    )
  }
}

// m-koa/m-book/src/views/Detail.vue
<template>
  <div>
    <img :src="detail.avatar" alt />
    <div>
      <button v-if="detail.is_in_my_book">已收藏</button>
      <button v-else @click="handleAdd(detail)">收藏</button>
    </div>
    <div>
      {{detail.summary}}
    </div>
  </div>
</template>

<script>
import Api from "../api";

export default {
  data() {
    return {
      detail: {}
    };
  },
  methods: {
    handleAdd(book) {
      Api.add({ book }).then(res => {
        if (res.code === 200) {
          this.detail.is_in_my_book = true
        }
      })
    }
  },
  mounted() {
    let { id } = this.$route.params;
    Api.getDetail(`?id=${id}`).then(res => {
      if (res.code === 200) {
        this.detail = res.data;
      }
    });
  }
};
</script>

<style>
</style>
