// m-react-app-test/src/views/Detail.js
import React, { useState, useEffect } from 'react'
import { connect } from 'react-redux'
import Api from '../api'

const Detail = (props) => {
  const [ detail, setDetail ] = useState({})

  const handleAdd = (item) => {
    let { bookList } = props
    let bookListClone = JSON.parse(JSON.stringify(bookList))
    item.checked = true
    item.count = 1
    bookListClone.push(item)
    props.setState('bookList', bookListClone)
    Api.add({item}).then(res => {
      if (res.data.code === 200) {

      }
    })
  }

  useEffect(() => {
    let { id } = props.match.params
    Api.getDetail(`?id=${id}`).then(res => {
      if (res.data.code === 200) {
        setDetail(res.data.data)
      }
    })

    Api.getBookList().then(res => {
      if (res.data.code === 200) {
        //props.setState('bookList', res.data.data)
      }
    })
  }, [])

  let { bookList } = props

  return (
    <div>
      <img src={detail.avatar} alt={detail.title}></img>,价格：{detail.price}元
      {
          bookList.find(book => book.id === detail.id)
          ? <button>已收藏</button>
          : <button onClick={handleAdd.bind(this, detail)}>收藏</button>
        }
    </div>
  )
}

const mapStateToProps = (state) => {
  return {
    bookList: state.bookList
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Detail)

// m-koa/m-book/src/views/Detail.vue
<template>
  <div>
    <img :src="detail.avatar" alt />
    <div>
      <button v-if="detail.is_in_my_book">已收藏</button>
      <button v-else @click="handleAdd(detail)">收藏</button>
    </div>
    <div>{{detail.summary}}</div>
  </div>
</template>

<script>
import Api from "../api";

export default {
  data() {
    return {
      detail: {}
    };
  },
  methods: {
    handleAdd(book) {
      if (!localStorage.getItem("username")) {
        this.$router.push("/login");
      }
      book.count = 1;
      book.checked = true;
      Api.add({ book }).then(res => {
        if (res.code === 200) {
          this.detail.is_in_my_book = true;
        }
      });
    }
  },
  mounted() {
    let { id } = this.$route.params;
    Api.getDetail(`?id=${id}`).then(res => {
      if (res.code === 200) {
        this.detail = res.data;
      }
    });
  }
};
</script>

<style>
</style>
