// m-react-app-test/src/views/Index.js
import React, { Component, Suspense, lazy } from 'react'
import { Route, Switch, NavLink, Redirect } from 'react-router-dom'
import Home from './Home'
//import MyBook from './MyBook'
import Detail from './Detail'
const MyBook = lazy(() => import('./MyBook'))

export default class Index extends Component {
  render() {
    return (
      <div>
        <div>
          <NavLink to="/index/home" className="m-nav-item">首页</NavLink>
          <NavLink to="/index/book" className="m-nav-item">书包</NavLink>
        </div>
        <Suspense fallback={<div>loading...</div>}>
          <Switch>
            <Route exact path="/index/home" component={Home}></Route>
            <Route path="/index/book" render={() => {
              if (localStorage.getItem('username')) {
                return <MyBook></MyBook>
              } else {
                return <Redirect to="/login"></Redirect>
              }
            }}></Route>
            <Route path="/index/home/detail/:id" component={Detail}></Route>
          </Switch>
        </Suspense>
      </div>
    )
  }
}

// m-koa/m-book/src/views/Index.vue
<template>
  <div>
    <div>
      <router-link to="/index/home" class="m-nav-item">首页</router-link>
      <router-link to="/index/my_book" class="m-nav-item">书包</router-link>
    </div>
    <div class="m-user" v-if="username">用户名:{{username}} <button @click="handleQuit()">退出</button></div>
    <div class="m-user" v-else><button @click="handleLogin()">登录</button></div>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  data() {
    return {
      username: ''
    }
  },
  methods: {
    handleQuit() {
      localStorage.removeItem('username')
      this.username = ''
    },
    handleLogin() {
      this.$router.push('/login')
    }
  },
  mounted() {
    this.username = localStorage.getItem('username')
  }
}
</script>

<style>

</style>
