// m-react-app/src/views/MyBook.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import axios from 'axios'

class MyBook extends Component {
  constructor(props) {
    super(props)
    this.state = {
      selectAll: false
    }
  }

  handleSelect(index, e) {
    let { myBook } = this.props
    myBook[index].checked = e.target.checked
    const count = myBook.filter(item => item.checked).length
    this.setState({
      selectAll: count === myBook.length
    })

    this.props.onSetState('myBook', myBook)
  }

  handleDelete(ids) {
    axios({
      url: '/api/delete_book',
      data: {
        ids
      },
      method: 'post'
    }).then(res => {
      if (res.data.code === 200) {
        this.props.onSetState('myBook', res.data.data)
      }
    })
  }

  handleDeleteMore() {
    let { myBook } = this.props
    let ids = myBook.filter(item => item.checked).map(item => item.id)
    axios({
      url: '/api/delete_book',
      data: {
        ids
      },
      method: 'post'
    }).then(res => {
      if (res.data.code === 200) {
        this.props.onSetState('myBook', res.data.data)
      }
    })
  }

  handleSelectAll(e) {
    let { myBook } = this.props
    this.setState({
      selectAll: e.target.checked
    })
    myBook.forEach(item => {
      item.checked = e.target.checked
    })
    this.props.onSetState('myBook', myBook)
  }

  handleAdd(index) {
    let { myBook } = this.props
    myBook[index].count = myBook[index].count + 1
    this.props.onSetState('myBook', myBook)
  }

  handleSub(index) {
    let { myBook } = this.props
    if (myBook[index].count > 1) {
      myBook[index].count = myBook[index].count - 1
      this.props.onSetState('myBook', myBook)
    }
  }

  total(myBook) {
    let totalPrice = 0, totalCount = 0
    myBook.filter(item => item.checked).forEach(item => {
      totalCount += item.count
      totalPrice += item.count * item.price
    })
    return {
      totalCount,
      totalPrice
    }
  }

  componentDidUpdate() {
    let { myBook } = this.props
    axios({
      url: '/api/update_my_book',
      data: {
        myBookNew: myBook
      },
      method: 'post'
    }).then(res => {
      if (res.data.code === 200) {
      }
    })
  }

  componentDidMount() {
    axios({
      url: '/api/get_my_book'
    }).then(res => {
      if (res.data.code === 200) {
        let myBook = res.data.data
        this.props.onSetState('myBook', myBook)
        const count = myBook.filter(item => item.checked).length
        this.setState({
          selectAll: count === myBook.length
        })
      }
    })
  }

  render() {
    let { myBook } = this.props
    let { selectAll } = this.state

    let myBookDom = myBook.map((item, index) => (
      <div key={item.id}>
        <input type="checkbox" checked={ item.checked } onChange={this.handleSelect.bind(this, index)}/>
        {item.title}，价格：{item.price}元<button onClick={this.handleSub.bind(this, index)}>-</button>{item.count}<button onClick={this.handleAdd.bind(this, index)}>+</button>
        <button onClick={this.handleDelete.bind(this, [item.id])}>删除</button>
      </div>
    ))

    let total = this.total(myBook)

    return (
      <div>
        <input type="checkbox" checked={selectAll} onChange={this.handleSelectAll.bind(this)}></input>全选
        <button onClick={this.handleDeleteMore.bind(this)}>删除</button>
        {myBookDom}
        <div>
          总价：{total.totalPrice}元,总数：{total.totalCount}
        </div>
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    myBook: state.myBook,
    a: [], //容错用的，可以是空数组，或空对象，删除这个加加减减将失效，原因未知！！！另一种解决办法是dispatch前深拷贝myBook
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBook)

// m-koa/m-book/src/views/MyBook.vue
<template>
  <div>
    <div v-for="(item, index) in myBook" :key="item.id">
      <input type="checkbox" :checked="item.checked" @change="handleChecked(index, $event)" :id="item.id">
      <label :for="item.id">{{item.title}}</label>
      ,￥{{item.price}} 
      <button @click="handleSub(index)">-</button> <span>{{item.count}}</span> <button @click="handleAdd(index)">+</button>
      <button @click="handleDelete(index)">删除</button>
    </div>
    <div>
      <input type="checkbox" :checked="total.selectAll" id="m-select-all" @change="handleSelectAll($event)">
      <label for="m-select-all">全选</label> <button @click="handleDeleteAll()">删除</button>
    </div>
    <div>
      总价：￥{{total.totalPrice}}，总数：{{total.totalCount}}
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    myBook() {
      return this.$store.state.myBook
    },
    total() {
      let myBook = this.$store.state.myBook
      let totalPrice = 0, totalCount = 0
      myBook.filter(item => item.checked).forEach(item => {
        totalCount += item.count
        totalPrice += item.count * item.price
      })
      return {
        totalPrice,
        totalCount,
        selectAll: myBook.filter(item => item.checked).length === myBook.length
      }
    }
  },
  methods: {
    handleDelete(index) {
      this.myBook.splice(index, 1)
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleDeleteAll() {
      let myBook = this.myBook.filter(item => !item.checked)
      this.$store.commit({ type: 'setState', key: 'myBook', value: myBook })
    },
    handleAdd(index) {
      this.myBook[index].count += 1
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleSub(index) {
      if (this.myBook[index].count > 1) {
        this.myBook[index].count -= 1
        this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
      }
    },
    handleChecked(index, e) {
      this.myBook[index].checked = e.target.checked
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    },
    handleSelectAll(e) {
      this.myBook.forEach(item => {
        item.checked = e.target.checked 
      })
      this.$store.commit({ type: 'setState', key: 'myBook', value: this.myBook })
    }
  },
  updated() {
    this.$store.dispatch({ type: 'updateMyBook', myBook: this.myBook })
  },
  mounted() {
    this.$store.dispatch({ type: 'getMyBook' })
  }
}
</script>

<style>

</style>
